#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Configuration loading and defaults."""

import copy
from pathlib import Path
from typing import Any, Dict, Optional

from .utils import deep_update, load_json


DEFAULT_CONFIG: Dict[str, Any] = {
    "paths": {
        "tonypi_root": "/home/pi/TonyPi",
        "tonypi_sdk": "/home/pi/TonyPi/HiwonderSDK",
        "action_group_dir": "/home/pi/TonyPi/ActionGroups",
        "camera_calibration": "/home/pi/robot_tonypi/camera_distortion_calibration/calibration_param.npz",
        "debug_root": "/home/pi/TonyPi/debug_runs",
    },
    "camera": {
        "forward_offset_cm": 0.0,
        "head_center_angle": 100.0,
        "head_left_angle": 145.0,
        "head_right_angle": 55.0,
        "head_tilt_center_pulse": 1500,
        "head_move_ms": 600,
        "settle_s": 0.55,
        "discard_frames": 3,
        "frame_gap_s": 0.08,
        "default_matrix": [
            [442.7764263403395, 0.0, 312.0124313067304],
            [0.0, 442.27334821002967, 221.54782360751392],
            [0.0, 0.0, 1.0],
        ],
        "default_dist_coeff": [
            -0.3563573203841699,
            0.16913777232573327,
            0.0,
            0.0,
            0.0,
        ],
    },
    "map": {
        "width_cm": 300.0,
        "height_cm": 300.0,
        "grid_resolution_cm": 5.0,
        "obstacle_inflation_cm": 28.0,
        "obstacle_hard_margin_cm": 8.0,
        "obstacle_cost_max": 80.0,
        "obstacle_cost_power": 2.0,
        "obstacle_line_clear_max_cost": 60.0,
        "excluded_screen_ids": [4, 6, 10, 20, 25],
    },
    "localization": {
        "tag_family": "tag36h11",
        "detector_upscale": 1.5,
        "min_tag_area_px": 350.0,
        "edge_margin_px": 35.0,
        "allowed_min_id": 1,
        "allowed_max_id": 36,
        "startup_attempts": 14,
        "startup_search_actions": ["turn_left_fast", "turn_left_fast", "turn_left_fast", "turn_left_fast", "back_fast"],
        "scan_pan_angles": [100, 135, 65, 155, 45],
        "high_confidence_tag_area_scale": 2.0,
    },
    "vision": {
        "scan_after_turn_enabled": True,
        "scan_after_turn_min_interval_s": 1.0,
        "harvest_pan_angles": [100, 130, 70],
        "vote_frames": 1,
        "min_votes": 1,
        "min_confidence": 0.20,
        "min_screen_area_px": 100.0,
        "max_screen_area_ratio": 0.98,
        "min_aspect_ratio": 0.25,
        "max_aspect_ratio": 4.8,
        "max_screen_width_height_ratio": 1.0,
        "max_side_ratio": 4.0,
        "white_threshold": 210,
        "max_center_white_ratio": 0.82,
        "max_tagged_center_white_ratio": 0.96,
        "tag_bind_max_px": 170.0,
        "tag_bind_diag_ratio": 0.85,
        "max_candidates_per_frame": 8,
        "map_visible_max_distance_cm": 125.0,
        "map_visible_min_distance_cm": 16.0,
        "map_visible_half_fov_deg": 34.0,
        "screen_front_max_angle_deg": 82.0,
    },
    "navigation": {
        "arrival_radius_cm": 23.0,
        "arrival_yaw_tolerance_deg": 30.0,
        "target_arrival_radius_cm": 4.0,
        "target_arrival_yaw_tolerance_deg": 10.0,
        "target_direct_approach_distance_cm": 40.0,
        "target_direct_corridor_half_width_cm": 6.0,
        "target_direct_non_target_max_cost": 60.0,
        "target_direct_min_component_cm": 2.0,
        "target_direct_forward_fast_min_cm": 10.0,
        "turn_tolerance_deg": 20.0,
        "relocalize_after_actions": 8,
        "relocalize_after_actions_high": 8,
        "relocalize_after_actions_medium": 4,
        "relocalize_after_actions_low": 1,
        "max_steps_per_target": 80,
        "safe_wall_distance_cm": 17.0,
        "near_wall_backoff_step_cm": 5.0,
        "near_wall_backoff_max_attempts": 3,
        "near_wall_lateral_step_cm": 4.0,
        "near_wall_lateral_max_attempts": 2,
        "near_wall_turn_step_deg": 7.5,
        "near_wall_recovery_no_progress_threshold": 2,
        "near_wall_min_clearance_improvement_cm": 1.5,
        "near_wall_max_action_cycles": 1,
        "recovery_max_action_cycles": 1,
        "near_wall_recovery_max_total_actions": 12,
        "near_wall_recovery_relocalize_each_action": True,
        "preserve_target_during_recovery": True,
        "near_wall_recovery_abandons_target": False,
        "max_turn_cycles_per_step": 4,
        "large_turn_threshold_deg": 35.0,
        "max_large_turn_cycles_per_step": 2,
        "adaptive_action_batch_enabled": True,
        "max_forward_cycles_high": 8,
        "max_forward_cycles_medium": 4,
        "max_forward_cycles_low": 1,
        "max_strafe_cycles_high": 4,
        "max_strafe_cycles_medium": 2,
        "max_strafe_cycles_low": 1,
        "max_reverse_cycles_high": 6,
        "max_reverse_cycles_medium": 3,
        "max_reverse_cycles_low": 1,
        "max_turn_cycles_high": 2,
        "max_turn_cycles_medium": 1,
        "max_turn_cycles_low": 1,
        "near_target_max_action_cycles": 1,
        "near_target_distance_cm": 40.0,
        "forward_uncertainty_per_cycle": 0.6,
        "strafe_uncertainty_per_cycle": 1.0,
        "turn_uncertainty_per_cycle": 1.8,
        "reverse_uncertainty_per_cycle": 0.9,
        "relocalize_uncertainty_threshold": 7.0,
        "localization_fresh_high_s": 4.0,
        "localization_fresh_medium_s": 10.0,
        "localization_pose_conflict_distance_cm": 15.0,
        "localization_pose_conflict_yaw_deg": 25.0,
        "relocalize_after_each_action_batch": True,
        "replan_after_each_action_batch": True,
        "strafe_min_lateral_cm": 7.0,
        "strafe_prefer_max_yaw_deg": 115.0,
        "translation_prefer_enabled": True,
        "translation_min_forward_cm": 6.0,
        "translation_min_progress_cm": 2.0,
        "translation_max_backward_cm": 8.0,
        "translation_corridor_half_width_cm": 8.0,
        "normal_navigation_max_cost": 55.0,
        "normal_wall_clearance_target_cm": 25.0,
        "normal_wall_clearance_penalty_scale": 4.0,
        "normal_path_obstacle_cost_scale": 0.35,
        "normal_path_action_switch_penalty_cm": 10.0,
        "turn_sweep_radius_cm": 10.0,
        "reverse_prefer_enabled": True,
        "reverse_prefer_rear_angle_tolerance_deg": 30.0,
        "reverse_prefer_min_distance_cm": 8.0,
        "reverse_prefer_max_lateral_cm": 8.0,
        "action_planner_reverse_cost": 1.08,
        "action_planner_reverse_step_cm": 10.0,
        "navigation_waypoint_lookahead_cm": 14.0,
        "navigation_waypoint_max_lookahead_cm": 0.0,
        "navigation_waypoint_forward_buffer_cm": 16.0,
        "action_planner_enabled": True,
        "action_planner_yaw_bin_deg": 15.0,
        "action_planner_forward_step_cm": 28.0,
        "action_planner_strafe_step_cm": 12.0,
        "action_planner_forward_cost": 1.0,
        "action_planner_strafe_cost": 1.05,
        "action_planner_turn_cost_cm_per_deg": 0.8,
        "action_planner_turn_fixed_cost_cm": 20.0,
        "action_planner_large_turn_extra_cost_cm": 12.0,
        "action_planner_consecutive_turn_penalty_cm": 20.0,
        "action_planner_reverse_turn_penalty_cm": 45.0,
        "action_planner_in_place_turn_penalty_cm": 18.0,
        "action_planner_path_reversal_penalty_cm": 35.0,
        "action_planner_away_from_goal_penalty_scale": 2.0,
        "action_planner_obstacle_cost_scale": 1.5,
        "action_planner_segment_max_cost": 55.0,
        "action_planner_wall_clearance_target_cm": 25.0,
        "action_planner_wall_clearance_penalty_scale": 4.0,
        "action_planner_goal_tolerance_cm": 8.0,
        "action_planner_max_expansions": 45000,
        "translation_path_prefer_enabled": True,
        "translation_path_min_component_cm": 8.0,
        "translation_path_max_detour_ratio": 1.45,
        "no_tag_recovery_enabled": True,
        "no_tag_recovery_failures": 2,
        "no_tag_recovery_cooldown_s": 4.0,
        "outward_exit_distance_cm": 62.0,
        "boundary_recovery_enabled": True,
        "boundary_trapped_margin_cm": 45.0,
        "boundary_recovery_goal_radius_cm": 20.0,
        "boundary_recovery_max_steps": 18,
        "boundary_recovery_max_target_distance_cm": 170.0,
        "boundary_recovery_center_pull_cm": 65.0,
        "boundary_outward_look_exit_cm": 75.0,
        "boundary_safe_turn_enabled": True,
        "collision_recovery_enabled": True,
        "collision_recovery_back_steps": 9,
        "collision_recovery_localize_attempts": 3,
        "collision_recovery_turn_attempts": 3,
        "forward_clearance_margin_cm": 10.0,
        "forward_map_obstacle_check_enabled": False,
        "forward_map_check_min_cm": 16.0,
        "forward_map_block_recover_limit": 2,
        "progress_check_enabled": True,
        "progress_check_expected_cm": 18.0,
        "progress_check_min_actual_cm": 6.0,
        "progress_check_fail_limit": 2,
        "visual_progress_check_enabled": True,
        "visual_progress_expected_cm": 12.0,
        "visual_progress_fail_limit": 2,
        "visual_progress_resize_width": 160,
        "visual_progress_min_absdiff": 4.5,
        "visual_progress_min_feature_shift_px": 1.8,
        "visual_progress_min_tracked_features": 12,
        "reserve_stop_distance_cm": 14.0,
    },
    "motion": {
        "imu_yaw_scale": 25.5,
        "enable_imu": False,
        "actions": {
            "stand": {"group": "stand", "times": 1, "with_stand": False, "settle_s": 0.25},
            "forward_fast": {"group": "go_forward_fast", "times": 1, "with_stand": True, "forward_cm": 3.5, "settle_s": 0.35},
            "forward_micro": {"group": "go_forward_one_small_step", "times": 1, "with_stand": False, "forward_cm": 2.0, "settle_s": 0.25},
            "interaction_forward_10cm": {
                "sequence": [
                    {"group": "go_forward_one_step", "times": 2, "with_stand": False},
                ],
                "times": 1,
                "forward_cm": 10.0,
                "settle_s": 0.30,
            },
            "back_fast": {
                "sequence": [
                    {"group": "back_start", "times": 1, "with_stand": False},
                    {"group": "back", "times": 1, "repeat": True, "with_stand": False},
                    {"group": "back_end", "times": 1, "with_stand": False}
                ],
                "times": 2,
                "forward_cm": -2.5,
                "settle_s": 0.35
            },
            "turn_left_large": {
                "sequence": [
                    {"group": "turn_left_small_step_s80", "times": 4, "repeat": True, "with_stand": False}
                ],
                "times": 1,
                "yaw_deg": 15.0,
                "settle_s": 0.12
            },
            "turn_right_large": {
                "sequence": [
                    {"group": "turn_right_small_step_s80", "times": 4, "repeat": True, "with_stand": False}
                ],
                "times": 1,
                "yaw_deg": -18.0,
                "settle_s": 0.12
            },
            "turn_left_fast": {"group": "turn_left_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": 7.5, "settle_s": 0.12},
            "turn_right_fast": {"group": "turn_right_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": -7.5, "settle_s": 0.12},
            "turn_left_micro": {"group": "turn_left_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": 7.5, "settle_s": 0.10},
            "turn_right_micro": {"group": "turn_right_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": -11.25, "settle_s": 0.10},
            "strafe_left_fast": {"group": "left_move_fast", "times": 1, "with_stand": False, "lateral_cm": 4.0, "settle_s": 0.35},
            "strafe_right_fast": {"group": "right_move_fast", "times": 1, "with_stand": False, "lateral_cm": -3.0, "settle_s": 0.35}
        },
    },
    "interaction": {
        "target_distance_cm": 19.0,
        "target_lateral_offset_cm": -1.5,
        "target_final_forward_cm": 10.0,
        "target_confirmation_max_retries": 3,
        "target_confirmation_retry_interval_s": 0.5,
        "target_confirmation_recovery_max_cycles": 2,
        "sensor_left_offset_cm": 5.0,
        # TonyPi left-hand center relative to body center along body-left.
        # No reliable mechanical measurement is available yet; calibrate on site.
        "left_hand_body_offset_cm": 0.0,
        "flower_change_scan_timeout_s": 0.0,
        "left_hand_settle_s": 0.5,
    },
    "mission": {
        "time_limit_s": 570.0,
        "target_success_count": 0,
        "max_main_loops": 10000,
        "max_target_attempts": 2,
        "continue_after_target_count": True,
    },
    "obstacle": {
        "enabled": True,
        "tag_min_id": 81,
        "min_area_px": 350.0,
        "center_band_ratio": 0.55,
        "dynamic_size_cm": 20.0,
        "dynamic_hard_margin_cm": 10.0,
    },
    "debug": {
        "enabled": False,
        "host": "127.0.0.1",
        "port": 8090,
        "save_images": True,
        "image_min_interval_s": 0.4,
        "dashboard": True,
    },
}


def load_config(path: Optional[str] = None) -> Dict[str, Any]:
    config = copy.deepcopy(DEFAULT_CONFIG)
    if path:
        override = load_json(path)
        deep_update(config, override)
    return config


def default_config_path() -> Path:
    return Path(__file__).resolve().parent / "config" / "competition_config.json"
