#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Configuration loading and defaults."""

import copy
from pathlib import Path
from typing import Any, Dict, Optional

from .utils import deep_update, load_json


DEFAULT_CONFIG: Dict[str, Any] = {
    "paths": {
        "tonypi_root": "/home/pi/TonyPi",
        "tonypi_sdk": "/home/pi/TonyPi/HiwonderSDK",
        "action_group_dir": "/home/pi/robot_tonypi/action_groups",
        "camera_calibration": "/home/pi/TonyPi/Functions/CameraCalibration/calibration_param.npz",
        "debug_root": "/home/pi/TonyPi/debug_runs",
    },
    "camera": {
        "forward_offset_cm": 0.0,
        "head_center_angle": 100.0,
        "head_left_angle": 145.0,
        "head_right_angle": 55.0,
        "head_tilt_center_pulse": 1500,
        "head_move_ms": 600,
        "settle_s": 0.55,
        "discard_frames": 3,
        "frame_gap_s": 0.08,
        "default_matrix": [[441.5962, 0.0, 290.2693], [0.0, 441.6984, 278.6220], [0.0, 0.0, 1.0]],
        "default_dist_coeff": [-0.3405, 0.1252, 0.0, 0.0],
    },
    "map": {
        "width_cm": 300.0,
        "height_cm": 300.0,
        "grid_resolution_cm": 5.0,
        "obstacle_inflation_cm": 28.0,
        "obstacle_hard_margin_cm": 8.0,
        "obstacle_cost_max": 80.0,
        "obstacle_cost_power": 2.0,
        "obstacle_line_clear_max_cost": 60.0,
        "observe_distance_cm": 48.0,
        "approach_margin_cm": 30.0,
        "excluded_screen_ids": [4, 6, 10, 20, 25],
    },
    "localization": {
        "tag_family": "tag36h11",
        "detector_upscale": 1.5,
        "min_tag_area_px": 350.0,
        "edge_margin_px": 35.0,
        "allowed_min_id": 1,
        "allowed_max_id": 36,
        "startup_attempts": 14,
        "startup_search_actions": ["turn_left_fast", "turn_left_fast", "turn_left_fast", "turn_left_fast", "back_fast"],
        "scan_pan_angles": [100, 135, 65, 155, 45],
    },
    "vision": {
        "harvest_during_localize_enabled": True,
        "scan_after_turn_enabled": True,
        "scan_after_turn_min_interval_s": 1.0,
        "harvest_pan_angles": [100, 130, 70],
        "opportunistic_pan_angles": [100],
        "vote_frames": 1,
        "min_votes": 1,
        "min_confidence": 0.20,
        "min_screen_area_px": 100.0,
        "max_screen_area_ratio": 0.85,
        "min_aspect_ratio": 0.25,
        "max_aspect_ratio": 4.8,
        "max_screen_width_height_ratio": 1.0,
        "max_side_ratio": 4.0,
        "white_threshold": 210,
        "max_center_white_ratio": 0.82,
        "max_tagged_center_white_ratio": 0.96,
        "tag_bind_max_px": 170.0,
        "tag_bind_diag_ratio": 0.85,
        "max_candidates_per_frame": 8,
        "map_visible_max_distance_cm": 125.0,
        "map_visible_min_distance_cm": 16.0,
        "map_visible_half_fov_deg": 34.0,
        "screen_front_max_angle_deg": 82.0,
        "opportunistic_enabled": True,
        "opportunistic_min_interval_s": 2.0,
        "opportunistic_min_move_cm": 12.0,
        "opportunistic_max_pans": 1,
        "periodic_full_scan_s": 35.0,
        "recheck_completed_screens_enabled": True,
        "recheck_completed_screen_reasons": [
            "route_passby",
            "navigate_step",
            "loop_start",
            "periodic_full_scan",
            "initial_discovery_scan",
            "scan_after_turn",
        ],
        "harvest_during_localize_recheck_completed": True,
    },
    "navigation": {
        "arrival_radius_cm": 23.0,
        "arrival_yaw_tolerance_deg": 30.0,
        "turn_tolerance_deg": 20.0,
        "relocalize_after_actions": 6,
        "max_steps_per_target": 80,
        "safe_wall_distance_cm": 17.0,
        "max_turn_cycles_per_step": 4,
        "large_turn_threshold_deg": 35.0,
        "max_large_turn_cycles_per_step": 2,
        "max_forward_cycles_high": 8,
        "max_forward_cycles_medium": 4,
        "max_forward_cycles_low": 2,
        "max_strafe_cycles_high": 6,
        "max_strafe_cycles_medium": 4,
        "max_strafe_cycles_low": 2,
        "strafe_min_lateral_cm": 7.0,
        "strafe_prefer_max_yaw_deg": 115.0,
        "translation_prefer_enabled": True,
        "translation_min_forward_cm": 6.0,
        "translation_min_progress_cm": 2.0,
        "translation_max_backward_cm": 8.0,
        "navigation_waypoint_lookahead_cm": 14.0,
        "navigation_waypoint_max_lookahead_cm": 0.0,
        "navigation_waypoint_forward_buffer_cm": 16.0,
        "action_planner_enabled": True,
        "action_planner_yaw_bin_deg": 15.0,
        "action_planner_forward_step_cm": 28.0,
        "action_planner_strafe_step_cm": 12.0,
        "action_planner_forward_cost": 1.0,
        "action_planner_strafe_cost": 1.0,
        "action_planner_turn_cost_cm_per_deg": 1.1,
        "action_planner_turn_fixed_cost_cm": 8.0,
        "action_planner_large_turn_extra_cost_cm": 4.0,
        "action_planner_obstacle_cost_scale": 1.0,
        "action_planner_segment_max_cost": 85.0,
        "action_planner_goal_tolerance_cm": 8.0,
        "action_planner_max_expansions": 45000,
        "translation_path_prefer_enabled": True,
        "translation_path_min_component_cm": 8.0,
        "translation_path_max_detour_ratio": 1.45,
        "turn_cost_cm_per_deg": 0.65,
        "route_screen_bonus_cm": 100.0,
        "route_sample_step_cm": 24.0,
        "route_passby_scan_enabled": True,
        "route_passby_include_completed_screens": True,
        "route_passby_pan_angles": [130, 70, 100],
        "route_passby_min_score": 0.22,
        "route_passby_min_ahead_cm": 50.0,
        "route_passby_max_ahead_cm": 95.0,
        "route_passby_arrival_radius_cm": 12.0,
        "route_passby_merge_distance_cm": 28.0,
        "route_passby_require_side": True,
        "route_passby_cooldown_s": 22.0,
        "route_passby_repeat_distance_cm": 45.0,
        "route_passby_max_pans": 2,
        "no_tag_recovery_enabled": True,
        "no_tag_recovery_failures": 2,
        "no_tag_recovery_cooldown_s": 4.0,
        "outward_exit_distance_cm": 62.0,
        "boundary_recovery_enabled": True,
        "boundary_trapped_margin_cm": 45.0,
        "boundary_recovery_goal_radius_cm": 20.0,
        "boundary_recovery_max_steps": 18,
        "boundary_recovery_max_target_distance_cm": 170.0,
        "boundary_recovery_center_pull_cm": 65.0,
        "boundary_outward_look_exit_cm": 75.0,
        "boundary_safe_turn_enabled": True,
        "collision_recovery_enabled": True,
        "collision_recovery_back_steps": 9,
        "collision_recovery_localize_attempts": 3,
        "collision_recovery_turn_attempts": 3,
        "forward_clearance_margin_cm": 10.0,
        "forward_map_obstacle_check_enabled": False,
        "forward_map_check_min_cm": 16.0,
        "forward_map_block_recover_limit": 2,
        "progress_check_enabled": True,
        "progress_check_expected_cm": 18.0,
        "progress_check_min_actual_cm": 6.0,
        "progress_check_fail_limit": 2,
        "visual_progress_check_enabled": True,
        "visual_progress_expected_cm": 12.0,
        "visual_progress_fail_limit": 2,
        "visual_progress_resize_width": 160,
        "visual_progress_min_absdiff": 4.5,
        "visual_progress_min_feature_shift_px": 1.8,
        "visual_progress_min_tracked_features": 12,
        "reserve_stop_distance_cm": 14.0,
        "target_body_reaim_enabled": True,
        "target_body_reaim_min_deg": 12.0,
    },
    "motion": {
        "imu_yaw_scale": 25.5,
        "enable_imu": False,
        "actions": {
            "stand": {"group": "stand", "times": 1, "with_stand": False, "settle_s": 0.25},
            "forward_fast": {"group": "go_forward_fast", "times": 1, "with_stand": True, "forward_cm": 3.5, "settle_s": 0.35},
            "forward_micro": {"group": "go_forward_one_small_step", "times": 1, "with_stand": False, "forward_cm": 2.0, "settle_s": 0.25},
            "back_fast": {
                "sequence": [
                    {"group": "back_start", "times": 1, "with_stand": False},
                    {"group": "back", "times": 1, "repeat": True, "with_stand": False},
                    {"group": "back_end", "times": 1, "with_stand": False}
                ],
                "times": 2,
                "forward_cm": -2.0,
                "settle_s": 0.35
            },
            "turn_left_large": {
                "sequence": [
                    {"group": "turn_left_small_step_s80", "times": 4, "repeat": True, "with_stand": False}
                ],
                "times": 1,
                "yaw_deg": 30.0,
                "settle_s": 0.12
            },
            "turn_right_large": {
                "sequence": [
                    {"group": "turn_right_small_step_s80", "times": 4, "repeat": True, "with_stand": False}
                ],
                "times": 1,
                "yaw_deg": -45.0,
                "settle_s": 0.12
            },
            "turn_left_fast": {"group": "turn_left_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": 7.5, "settle_s": 0.12},
            "turn_right_fast": {"group": "turn_right_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": -11.25, "settle_s": 0.12},
            "turn_left_micro": {"group": "turn_left_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": 7.5, "settle_s": 0.10},
            "turn_right_micro": {"group": "turn_right_small_step_s80", "times": 1, "with_stand": False, "yaw_deg": -11.25, "settle_s": 0.10},
            "strafe_left_fast": {"group": "left_move_fast", "times": 1, "with_stand": False, "lateral_cm": 4.0, "settle_s": 0.35},
            "strafe_right_fast": {"group": "right_move_fast", "times": 1, "with_stand": False, "lateral_cm": -4.0, "settle_s": 0.35}
        },
    },
    "interaction": {
        "interaction_distance_cm": 15.0,
        "interaction_distance_tolerance_cm": 4.0,
        "interaction_yaw_tolerance_deg": 10.0,
        "sensor_left_offset_cm": 5.0,
        "interaction_lateral_tolerance_cm": 4.0,
        # TonyPi left-hand center relative to body center along body-left.
        # No reliable mechanical measurement is available yet; calibrate on site.
        "left_hand_body_offset_cm": 0.0,
        "interaction_staging_distance_cm": 34.0,
        "interaction_staging_arrival_radius_cm": 8.0,
        "interaction_pose_max_age_s": 3.0,
        "interaction_pose_min_confidence": "HIGH",
        "interaction_relocalize_before_action": True,
        "interaction_relocalize_each_step": True,
        "interaction_max_alignment_steps": 20,
        "flower_change_scan_timeout_s": 0.0,
        "left_hand_settle_s": 0.5,
        # screen_id -> worker_id. Empty by default because this repository does
        # not prove that visual screen IDs and Worker IDs are identical.
        "worker_mapping": {},
    },
    "mission": {
        "time_limit_s": 570.0,
        "target_success_count": 0,
        "max_main_loops": 10000,
        "initial_discovery_scan_enabled": True,
        "initial_discovery_scan_pan_angles": [130, 100, 70],
        "initial_discovery_scan_frames": 1,
        "initial_discovery_scan_left_turn_cycles": 4,
        "initial_discovery_scan_right_turn_cycles": 5,
        "initial_discovery_scan_relocalize_after": True,
        "continue_after_target_count": True,
    },
    "obstacle": {
        "enabled": True,
        "tag_min_id": 81,
        "min_area_px": 350.0,
        "center_band_ratio": 0.55,
        "dynamic_size_cm": 20.0,
        "dynamic_hard_margin_cm": 10.0,
    },
    "debug": {
        "enabled": False,
        "host": "127.0.0.1",
        "port": 8090,
        "save_images": True,
        "image_min_interval_s": 0.4,
        "dashboard": True,
    },
}


def load_config(path: Optional[str] = None) -> Dict[str, Any]:
    config = copy.deepcopy(DEFAULT_CONFIG)
    if path:
        override = load_json(path)
        deep_update(config, override)
    return config


def default_config_path() -> Path:
    return Path(__file__).resolve().parent / "config" / "competition_config.json"
